### ISSUE TITLE
ogg include error

### ISSUE THREAD

**Issue by santydr** [pschatzmann/arduino-libflac#2]
I'm trying to get a flac audio file played with AudioTools in Arduino IDE but I can't compile because I always get this error:

_In file included from C:\Users\emiri\Documents\Arduino\libraries\libflac\src/private/ogg_decoder_aspect.h:36,
                 from C:\Users\emiri\Documents\Arduino\libraries\libflac\src\libFLAC\ogg_decoder_aspect.c:39:
C:\Users\emiri\Documents\Arduino\libraries\libflac\src/ogg/ogg.h:3:10: fatal error: ../../src/libogg-1.3.5/include/ogg/ogg.h: No such file or directory
    3 | #include "../../src/libogg-1.3.5/include/ogg/ogg.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: exit status 1_

I have installed the last release and even cloned the repository but still doesn't work and I can see no other information online. I have used the code in posted in https://www.pschatzmann.ch/home/2022/05/14/a-flac-codec-for-the-arduino-audio-tools/

**Comment by pschatzmann** [comment]
https://github.com/pschatzmann/arduino-libflac?tab=readme-ov-file#dependencies
