### ISSUE TITLE
Missing src/libFLAC/window.c file

### ISSUE THREAD

**Issue by SaidAlvarado** [pschatzmann/arduino-libflac#3]
Hello !
First of all, thank you for creating this project. I'm trying to port LibFLAC to an nRF microcontroller, and this repo has been an incredibly useful reference.

I've noticed that this repository has a  `src/private/window.h` file, but no matching `src/libFLAC/window.c` file.
Yet, the `window.c` file exist in the official [FLAC repository](https://github.com/xiph/flac/blob/a0e30a4ef2539406bcb4bea63c2983eb98363b0f/src/libFLAC/window.c).
 
I  had to re-add this file to my port in order to get it to compile. 
So I kind of assumed it was important.

I thought you might appreciate the FYI.

Cheers !

**Comment by pschatzmann** [comment]
Strange: I never had any issues w/o it, but I added it back as you suggested
